services:
  mysql:
    container_name: gestao_vagas_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestao_vagas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    
volumes:
  mysql_data:
