networks:
  gv-network:
    driver: bridge

services:
  mysql:
    container_name: gestao_vagas_mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestao_vagas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - gv-network
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - "9091:9091"

volumes:
  mysql_data:
  prometheus_data: