networks:
  gv-network:
    driver: bridge

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestao_vagas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - gv-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - "9001:9001"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - gv-network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
