global:
  scrape_interval: 9s

scrape_configs:
  - job_name: "api_gestao_vagas"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
        labels:
          application: "api-gestao-vagas"
